config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/about", to: "static_pages#about"

  resources :blog_posts, path: "blog-posts"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id          :bigint           not null, primary key
#  body        :text
#  description :string
#  image       :string
#  published   :boolean          default(FALSE)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class BlogPost < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 256 }
  validates :description, presence: true, length: { minimum: 5, maximum: 256 }
  validates :body, presence: true, length: { minimum: 5 }

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }
  scope :latest, -> { order(updated_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.published.latest
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy

    redirect_to blog_posts_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :description, :body, :image, :published)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, options = {})
    options[:title] ||= name.underscore.humanize
    options[:aria] = true
    options[:nocomment] = true
    options[:class] = options.fetch(:class, "")

    filename = "#{name}.svg"
    inline_svg_tag(filename, options)
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/edit.html.erb
<h1 class="mb-5">Edit Article</h1>

<%= form_with model: @blog_post, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field mb-5">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field mb-5">
    <%= form.label "Publish" %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit class: "bg-indigo-500 text-white py-2 px-3" %>
  </div>
<% end %>

app/views/blog_posts/index.html.erb
<h1 class="mb-5">Blog Posts</h1>

<% @blog_posts.each do |blog_post| %>
  <%= link_to blog_post_path(blog_post) do  %>
    <article class="mb-3">
      <h2><%= blog_post.title %></h2>
      <p><%= blog_post.description %></p>
    </article>
  <% end %>
<% end %>

app/views/blog_posts/new.html.erb
<h1 class="mb-5">New Article</h1>

<%= form_with model: @blog_post, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field mb-5">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field mb-5">
    <%= form.label "Publish" %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit class: "bg-indigo-500 text-white py-2 px-3" %>
  </div>
<% end %>

app/views/blog_posts/show.html.erb
<h1 class="mb-5"><%= @blog_post.title %></h1>

<h3 class="mb-3"><%= @blog_post.description %></h3>

<article class="mb-5">
  <%= @blog_post.body %>
</article>

<div class="actions">
  <%= link_to "Edit", edit_blog_post_path(@blog_post),
                      class: "bg-indigo-500 text-white py-2 px-3" %>

  <%= link_to "Delete", blog_post_path(@blog_post),
                        method: :delete,
                        data: { turbo_confirm: "Are you sure?", 
                                turbo_method: :delete },
                        class: "bg-red-500 text-white py-2 px-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>leocsdev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= favicon_link_tag asset_path("favicon.png") %>
  </head>

  <body>
    <main class="font-heebo text-myBlack">
      <%= yield %>
    </main>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Me</h1>

app/views/static_pages/index.html.erb
<section id="hero" class="section-container px-4 py-10 flex flex-col justify-evenly text-center md:flex-row gap-4 md:justify-around md:items-center">
  <div class="my-10 md:my-0 md:w-[60%]">
    <h1 class="text-6xl lg:text-7xl font-bold mb-8 md:mb-4 lg:mb-8">
      <%= t(".heading") %>
    </h1>
    <p class="text-2xl md:text-3xl">
      <%= t(".subheading") %>
    </p>
  </div>
  <div class="md:w-[40%]">
    <%= render_svg("developer-activity-animate", class: "w-2/3 md:w-full mx-auto") %>
  </div>
</section>

<section id="recent-posts" class="bg-offWhite">
  <div class="section-container px-4 py-10">
    <div class="flex items-center justify-between mb-4">
      <h2 class="font-semibold text-[18px]">Recent Posts</h2>
      <h2 class="text-sm text-lightBlue hover:text-lightRed">
        <a href="#">View All</a>
      </h2>
    </div>

    <div class="flex flex-col gap-4 md:flex-row">
      <a href="#" class="bg-white p-6 rounded md:w-[50%] hover:shadow-lg hover:-translate-y-1 ease-in-out duration-200">
        <h2 class="mb-3 font-semibold text-[26px]">Escape Tutorial Hell Tips</h2>

        <p class="mb-4 text-[18px]">
          <span class="mr-4">2021-05-31</span> |
          <span class="ml-4 text-slate-500">Guide</span>
        </p>

        <p class="mb-4">I've been into tutorial hell, and it's not good. Here are some ways to escape from it.</p>
      </a>

      <a href="#" class="bg-white p-6 rounded md:w-[50%] hover:shadow-lg hover:-translate-y-1 ease-in-out duration-200">
        <h2 class="mb-3 font-semibold text-[26px]">Website Layout Without Design Skills, A Summary</h2>

        <p class="mb-4 text-[18px]">
          <span class="mr-4">2021-05-30</span> |
          <span class="ml-4 text-slate-500">Design</span>
        </p>

        <p class="mb-4">A guide on how to layout a website design even without design skils.</p>
      </a>
    </div>
  </div>
</section>

<section id="recent-projects">
  <div class="section-container px-4 py-10">
    <div class="flex items-center justify-between mb-4">
      <h2 class="font-semibold text-[18px]">Recent Projects</h2>
      <h2 class="text-sm text-[#00a8cc] hover:text-[#ff6464]">
        <a href="#">View All</a>
      </h2>
    </div>

    <ul class="grid md:grid-cols-2 gap-8">
      <li>
        <figure class="relative rounded-2xl">
          <%= image_tag("age-calculator-app-1080", class: "w-full h-[300px] md:h-[275px] object-cover rounded-2xl shadow-md") %>
          <figcaption
            class="absolute top-0 left-0 w-full h-full bg-darkBlue rounded-2xl p-4 transition-opacity duration-500 text-white opacity-0">
            <div class="w-full h-full flex flex-col items-center justify-center text-center">
              <h2 class="text-xl mb-2">Project name</h2>
              <p class="mb-4">Project description</p>
              <div class="flex gap-2">
                <a
                  href="#"
                  target="_blank"
                  class="border border-lightRed px-4 py-1 text-lightRed rounded-full hover:bg-lightRed hover:text-white transition-colors duration-300"
                >
                  Live Site
                </a>
                <a
                  href="#"
                  target="_blank"
                  class="border border-lightBlue px-4 py-1 text-lightBlue rounded-full hover:bg-lightBlue hover:text-white transition-colors duration-300"
                >
                  Source Code
                </a>
              </div>
            </div>
            <div class="absolute bottom-0 text-white left-[50%] -translate-x-[50%] translate-y-[50%]">
              <ul class="flex gap-1">
                <li class="w-[40px] h-[40px] bg-white p-[4px] rounded-full flex items-center justify-center shadow-[0_3px_5px_-2px_rgba(0,0,0,0.3)]">
                  <%= render_svg("rails", class: "w-full h-full rounded-full") %>
                </li>
                <li class="w-[40px] h-[40px] bg-white p-[4px] rounded-full flex items-center justify-center shadow-[0_3px_5px_-2px_rgba(0,0,0,0.3)]">
                  <%= render_svg("tailwind", class: "w-full h-full rounded-full") %>
                </li>
              </ul>
            </div>
          </figcaption>
        </figure>
      </li>
      <li>
        <figure class="relative rounded-2xl">
          <%= image_tag("trivia-whiz-app", class: "w-full h-[300px] md:h-[275px] object-cover rounded-2xl shadow-md") %>
          <figcaption
            class="absolute top-0 left-0 w-full h-full bg-darkBlue rounded-2xl p-4 transition-opacity duration-500 text-white opacity-100">
            <div class="w-full h-full flex flex-col items-center justify-center text-center">
              <h2 class="text-xl mb-2">Project name</h2>
              <p class="mb-4">Project description</p>
              <div class="flex gap-2">
                <a
                  href="#"
                  target="_blank"
                  class="border border-lightRed px-4 py-1 text-lightRed rounded-full hover:bg-lightRed hover:text-white transition-colors duration-300"
                >
                  Live Site
                </a>
                <a
                  href="#"
                  target="_blank"
                  class="border border-lightBlue px-4 py-1 text-lightBlue rounded-full hover:bg-lightBlue hover:text-white transition-colors duration-300"
                >
                  Source Code
                </a>
              </div>
            </div>
            <div class="absolute bottom-0 text-white left-[50%] -translate-x-[50%] translate-y-[50%]">
              <ul class="flex gap-1">
                <li class="w-[40px] h-[40px] bg-white p-[4px] rounded-full flex items-center justify-center shadow-[0_3px_5px_-2px_rgba(0,0,0,0.3)]">
                  <%= render_svg("rails", class: "w-full h-full rounded-full") %>
                </li>
                <li class="w-[40px] h-[40px] bg-white p-[4px] rounded-full flex items-center justify-center shadow-[0_3px_5px_-2px_rgba(0,0,0,0.3)]">
                  <%= render_svg("tailwind", class: "w-full h-full rounded-full") %>
                </li>
              </ul>
            </div>
          </figcaption>
        </figure>
      </li>
    </ul>
  </div>
</section>